Repository AY2425S1-CS2103T-F09-3/tp, pull requests merged in 2024-11, with the labels that each got.

#119 Further improve User Guide
  docs/UserGuide.md
  docs/images/addGuestCommand.png
  docs/images/addGuestCommandSample.png
  docs/images/addVendorCommand.png
  docs/images/addVendorCommandSample.png
  docs/images/clearCommand.png
  docs/images/deleteGuestCommand.png
  docs/images/deleteVendorCommand.png
  docs/images/deleteVendorCommandSample.png
  docs/images/editGuestCommand.png
  docs/images/editVendorCommand.png
  docs/images/findCommand.png
  docs/images/helpMessage.png
  docs/images/listCommand.png
  docs/images/statsCommand.png
Labels: priority.High

#124 Fix hyperlink issue in UG
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#123 Branch edit relation
  src/main/java/seedu/address/logic/commands/util/EditGuestDescriptor.java
  src/main/java/seedu/address/model/person/Rsvp.java
  src/test/java/seedu/address/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditGuestCommandParserTest.java
Labels: priority.High, alpha-bug

#126 Split add guest and add vendor in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, alpha-bug

#132 Split Add Person to Add Guest and Add Vendor in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, alpha-bug

#141 Specify restrictions in commands in UG
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#145 Add hyperlink of prefix to glossary
  docs/UserGuide.md
Labels: priority.Medium

#153 Remove irrelevant issue in UG
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#154 Add sub-headers for tutorial in table of contents
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High, alpha-bug

#169 Finalise UG for v1.5
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/Ui.png
  docs/images/addGuestCommand.png
  docs/images/addGuestCommandSample.png
  docs/images/addVendorCommand.png
  docs/images/addVendorCommandSample.png
  docs/images/clearCommand.png
  docs/images/deleteGuestCommand.png
  docs/images/deleteVendorCommand.png
  docs/images/deleteVendorCommandSample.png
  docs/images/editGuestCommand.png
  docs/images/editVendorCommand.png
  docs/images/findCommand.png
  docs/images/listCommand.png
  docs/images/statsCommand.png
Labels: priority.High, alpha-bug

#283 Partially fix UG
  docs/UserGuide.md
Labels: priority.High

#284 Branch enhance user guide
  docs/UserGuide.md
Labels: priority.High

#285 Further improve UG
  docs/UserGuide.md
Labels: priority.High

#287 Improvise UG
  docs/UserGuide.md
Labels: priority.High

#293 Improvise UG
  docs/UserGuide.md
Labels: priority.High

#294 Provide clarity in entering indexes
  docs/UserGuide.md
Labels: priority.High

#298 Add updated screenshots
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addGuestCommand.png
  docs/images/addGuestCommandSample.png
  docs/images/addVendorCommand.png
  docs/images/addVendorCommandSample.png
  docs/images/clearCommand.png
  docs/images/deleteGuestCommand.png
  docs/images/deleteVendorCommand.png
  docs/images/deleteVendorCommandSample.png
  docs/images/editGuestCommand.png
  docs/images/editVendorCommand.png
  docs/images/findCommand.png
  docs/images/firstUseUi.png
  docs/images/listCommand.png
  docs/images/statsCommand.png
Labels: priority.High

#306 UI draft
  docs/UserGuide.md
  docs/images/firstUseUI.png
  docs/images/firstUseUi.png
Labels: priority.High
